#!/bin/bash

# Export variables
export TERMINAL=urxvt
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_STYLE_OVERRIDE=gtk2

# Build configs before launching WM
rebuild-all-configs

# Merge .Xresources
xrdb -merge ~/.Xresources

# Start DE
exec gnome-session
